const $=id=>document.getElementById(id),money=n=>'$'+Number(n||0).toLocaleString('es-MX',{minimumFractionDigits:2});let user=null,cur=null;
const users=[{user:'Maedrs87',pass:'Zoom101p',role:'admin',name:'Admin'},{user:'Admin545',pass:'AdminGi116',role:'reader',name:'Lector'},{user:'innova',pass:'innnova',role:'agenda',name:'Agenda'}];
const seed={users,events:[{id:1,client:'Ana & Luis',type:'Boda',date:'2026-06-28',time:'18:00',place:'Hacienda San Carlos',amount:25000,comment:'Evento muestra',charges:[{type:'Anticipo',amount:10000,comment:'Apartado'}],expenses:[],members:[{name:'Pedro López',role:'Sax',salary:2000,paid:false}],admins:[{name:'Admin 1',amount:0,paid:false},{name:'Admin 2',amount:0,paid:false},{name:'Admin 3',amount:0,paid:false}],files:[]}],baseMembers:[{name:'Pedro López',role:'Sax',salary:2000},{name:'Luis García',role:'Teclado',salary:1800}]};
let db=JSON.parse(localStorage.getItem('gi_v63'))||JSON.parse(localStorage.getItem('gi_v62'))||seed;db.users=users;if(!db.baseMembers)db.baseMembers=seed.baseMembers;
function save(){localStorage.setItem('gi_v63',JSON.stringify(db));render();alert('Información guardada')}
function login(){user=users.find(u=>u.user===$('u').value&&u.pass===$('p').value);if(!user)return alert('Usuario o contraseña incorrectos');$('login').classList.add('hidden');$('app').classList.remove('hidden');nav();show(user.role==='agenda'?'agenda':'dashboard')}
function can(){return user&&user.role==='admin'}function nav(){let items=user.role==='agenda'?[['agenda','📅','Agenda']]:[['dashboard','🏠','Dashboard'],['agenda','📅','Agenda'],['events','💼','Eventos'],['membersBase','👥','Integrantes'],['cash','💵','Caja'],['reports','📊','Reportes'],['users','👥','Usuarios']];$('nav').innerHTML=items.map(i=>`<button id="n${i[0]}" class="navbtn" onclick="show('${i[0]}')">${i[1]}<br>${i[2]}</button>`).join('')}
function show(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.navbtn').forEach(b=>b.classList.remove('active'));let n=$('n'+id);if(n)n.classList.add('active');$('title').textContent=id==='dashboard'?'¡Bienvenido, '+user.name+'!':({agenda:'Agenda',events:'Eventos',membersBase:'Integrantes',cash:'Caja',reports:'Reportes',users:'Usuarios',detail:'Detalle del evento'}[id]||'Dashboard');render()}
function inc(e){return (e.charges||[]).reduce((a,b)=>a+Number(b.amount||0),0)}function exp(e){return (e.expenses||[]).reduce((a,b)=>a+Number(b.amount||0),0)}function sal(e){return (e.members||[]).reduce((a,b)=>a+Number(b.salary||0),0)}function base(e){return Math.max(0,inc(e)-exp(e)-sal(e))}function norm(){db.events.forEach(e=>{let b=base(e)/3;(e.admins||[]).forEach(a=>{if(!a.manual)a.amount=b})})}
function render(){norm();renderDash();renderAgenda();renderEvents();renderMembersBase();renderCash();renderReports();document.querySelectorAll('.admin').forEach(x=>x.style.display=can()?'':'none')}
function row(e){let d=new Date(e.date+'T00:00:00');return `<div class="row"><div class="date">${(e.date||'').slice(8,10)}<br>${d.toLocaleString('es-MX',{month:'short'}).toUpperCase()}</div><div class="mainrow"><b>${e.type} - ${e.client}</b><br><span>${e.time||''} · ${e.place}</span></div><span class="badge">Pendiente</span></div>`}
function renderDash(){let cash=db.events.reduce((a,e)=>a+inc(e)-exp(e),0)-db.events.flatMap(e=>e.members).filter(m=>m.paid).reduce((a,m)=>a+m.salary,0)-db.events.flatMap(e=>e.admins).filter(a=>a.paid).reduce((x,a)=>x+a.amount,0);let pending=db.events.reduce((a,e)=>a+Math.max(0,e.amount-inc(e)),0);$('ke').textContent=db.events.length;$('kc').textContent=money(cash);$('kp').textContent=money(pending);$('kl').textContent=money(cash);$('upcoming').innerHTML=db.events.map(row).join('')}
function renderAgenda(){$('agendaList').innerHTML=db.events.map(e=>`<div class="row"><div class="date">${(e.date||'').slice(8,10)}</div><div><b>${e.type}</b><br>${e.time||''}<br>${e.place}</div></div>`).join('')}
function clearForm(){['c','d','t','l','h','m','com'].forEach(id=>$(id).value='')}
function addEvent(){let e={id:Date.now(),client:$('c').value,type:$('t').value,date:$('d').value,time:$('h').value,place:$('l').value,amount:Number($('m').value||0),comment:$('com').value,charges:[],expenses:[],members:db.baseMembers.map(m=>({...m,paid:false})),admins:[{name:'Admin 1',amount:0,paid:false},{name:'Admin 2',amount:0,paid:false},{name:'Admin 3',amount:0,paid:false}],files:[]};db.events.push(e);clearForm();save()}
function renderEvents(){let q=($('q')?.value||'').toLowerCase();$('eventList').innerHTML=db.events.filter(e=>[e.client,e.type,e.date,e.place].join(' ').toLowerCase().includes(q)).map(e=>`<div class="row"><div onclick="openEvent(${e.id})" class="mainrow"><b>${e.type} - ${e.client}</b><br>${e.date} ${e.time||''}<br>${e.place} · ${money(e.amount)}</div>${can()?`<div class="actions"><button class="btn light small" onclick="editEvent(${e.id})">Editar</button><button class="btn danger small" onclick="delEvent(${e.id})">Eliminar</button></div>`:''}</div>`).join('')}
function editEvent(id){let e=db.events.find(x=>x.id===id);$('c').value=e.client;$('d').value=e.date;$('t').value=e.type;$('l').value=e.place;$('h').value=e.time;$('m').value=e.amount;$('com').value=e.comment||'';delEvent(id,false);show('dashboard')}
function delEvent(id,ask=true){if(ask&&!confirm('¿Eliminar evento?'))return;db.events=db.events.filter(e=>e.id!==id);save()}
function renderMembersBase(){$('membersBaseList').innerHTML=(db.baseMembers||[]).map((m,i)=>`<div class="row"><div class="mainrow"><b>${m.name}</b><br>${m.role}<br>Sueldo base: ${money(m.salary)}</div>${can()?`<div class="actions"><button class="btn light small" onclick="editBaseMember(${i})">Editar</button><button class="btn danger small" onclick="delBaseMember(${i})">Eliminar</button></div>`:''}</div>`).join('')||'<p>Sin integrantes.</p>'}
function addBaseMember(){db.baseMembers.push({name:prompt('Nombre'),role:prompt('Instrumento / función'),salary:Number(prompt('Sueldo base')||0)});save()}
function editBaseMember(i){let m=db.baseMembers[i];m.name=prompt('Nombre',m.name)||m.name;m.role=prompt('Instrumento / función',m.role)||m.role;m.salary=Number(prompt('Sueldo base',m.salary)||m.salary);save()}
function delBaseMember(i){if(confirm('¿Eliminar integrante base?')){db.baseMembers.splice(i,1);save()}}
function openEvent(id){cur=id;show('detail');tab('info')}
function ce(){return db.events.find(e=>e.id===cur)}function tab(t){let e=ce();$('head').innerHTML=`<h2>${e.type} - ${e.client}</h2><p>${e.date} · ${e.time||''} · ${e.place}</p><b>${money(e.amount)}</b>`;let h='';if(t==='info')h=`<h2>Información</h2><p>${e.comment||'Sin comentarios.'}</p>`;if(t==='charges')h=`<h2>Cobros</h2>${can()?`<div class="subform"><input id="ct" placeholder="Tipo"><input id="ca" type="number" placeholder="Monto"><input id="cc" placeholder="Comentario"><button class="btn primary" onclick="addCharge()">Guardar cobro</button></div>`:''}${e.charges.map((c,i)=>line(c.type,c.comment,money(c.amount),`editCharge(${i})`,`delCharge(${i})`)).join('')}`;if(t==='expenses')h=`<h2>Gastos</h2>${can()?`<div class="subform"><input id="gt" placeholder="Tipo de gasto"><input id="ga" type="number" placeholder="Monto"><input id="gd" placeholder="Descripción"><button class="btn primary" onclick="addExpense()">Guardar gasto</button></div>`:''}${e.expenses.map((g,i)=>line(g.type,g.desc,money(g.amount),`editExpense(${i})`,`delExpense(${i})`)).join('')}`;if(t==='members')h=`<h2>Integrantes</h2>${e.members.map((m,i)=>line(m.name,m.role,money(m.salary),`editMem(${i})`,`delMem(${i})`,m.paid,`togMem(${i})`)).join('')}`;if(t==='admins')h=`<h2>Administrativos</h2>${e.admins.map((a,i)=>line(a.name,'Utilidad',money(a.amount),`editAd(${i})`,`delAd(${i})`,a.paid,`togAd(${i})`)).join('')}`;if(t==='files')h=`<h2>Adjuntos</h2>${can()?`<button class="btn primary" onclick="$('file').click()">Adjuntar</button>`:''}${(e.files||[]).map((f,i)=>line('📎 '+f.name,f.type||'Archivo',f.size||'',`alert('Archivo registrado')`,`delFile(${i})`)).join('')}`;if(t==='summary')h=`<h2>Resumen</h2><p>Ingresos: ${money(inc(e))}</p><p>Gastos: ${money(exp(e))}</p><p>Sueldos: ${money(sal(e))}</p><p>Utilidad admins: ${money(base(e))}</p>`;$('content').innerHTML=h}
function line(a,b,c,edit,del,paid,toggle){return `<div class="line"><div><b>${a}</b><br><span>${b||''}</span>${can()?`<div class="actions"><button class="btn light small" onclick="${edit}">Editar</button><button class="btn danger small" onclick="${del}">Eliminar</button></div>`:''}</div><div>${c||''}${toggle?`<br><label><input type="checkbox" ${paid?'checked':''} onchange="${toggle}"> Pagado</label>`:''}</div></div>`}
function addCharge(){ce().charges.push({type:$('ct').value,amount:Number($('ca').value||0),comment:$('cc').value});save();tab('charges')}function editCharge(i){let c=ce().charges[i];c.type=prompt('Tipo',c.type)||c.type;c.amount=Number(prompt('Monto',c.amount)||c.amount);c.comment=prompt('Comentario',c.comment)||'';save();tab('charges')}function delCharge(i){ce().charges.splice(i,1);save();tab('charges')}
function addExpense(){ce().expenses.push({type:$('gt').value,amount:Number($('ga').value||0),desc:$('gd').value});save();tab('expenses')}function editExpense(i){let g=ce().expenses[i];g.type=prompt('Tipo',g.type)||g.type;g.amount=Number(prompt('Monto',g.amount)||g.amount);g.desc=prompt('Descripción',g.desc)||'';save();tab('expenses')}function delExpense(i){ce().expenses.splice(i,1);save();tab('expenses')}
function editMem(i){ce().members[i].salary=Number(prompt('Sueldo',ce().members[i].salary)||ce().members[i].salary);save();tab('members')}function delMem(i){ce().members.splice(i,1);save();tab('members')}function togMem(i){ce().members[i].paid=!ce().members[i].paid;save();tab('members')}
function editAd(i){let a=ce().admins[i];a.amount=Number(prompt('Monto',a.amount)||a.amount);a.manual=true;save();tab('admins')}function delAd(i){ce().admins.splice(i,1);save();tab('admins')}function togAd(i){ce().admins[i].paid=!ce().admins[i].paid;save();tab('admins')}
function files(ev){[...ev.target.files].forEach(f=>ce().files.push({name:f.name,type:f.type,size:(f.size/1024/1024).toFixed(2)+' MB'}));ev.target.value='';save();tab('files')}function delFile(i){ce().files.splice(i,1);save();tab('files')}
function renderCash(){let rows=[],s=0;db.events.forEach(e=>{e.charges.forEach(c=>{s+=c.amount;rows.push(line(c.type,e.type,money(s),'',''))});e.expenses.forEach(g=>{s-=g.amount;rows.push(line(g.type,e.type,money(s),'',''))})});$('cashList').innerHTML=rows.join('')||'<p>Sin movimientos.</p>'}function renderReports(){$('reportsBox').innerHTML=`<p>Eventos registrados: ${db.events.length}</p><p>Ingreso total: ${money(db.events.reduce((a,e)=>a+inc(e),0))}</p>`}render();